apiVersion: v1
kind: Service
metadata:
  name: rotisserie-app
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    nodePort: 30080
  selector:
    app: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rotisserie-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: rotisserie-app
        image: anthonyamanse/rotisserie-app
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: OCR_HOST
          value: rotisserie-ocr:3001
        - name: token
          valueFrom:
            secretKeyRef:
              name: rotisserie-secrets
              key: token
        - name: clientID
          valueFrom:
            secretKeyRef:
              name: rotisserie-secrets
              key: clientID
          #USE SECRET
