apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ template "rotisserie.fullname" . }}-letsencrypt-prod
  namespace: {{ .Values.namespace }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.certManager.url }}
    # Email address used for ACME registration
    email: {{ .Values.certManager.email }}
    # Name of a secret used to store the ACME account private key from step 3
    privateKeySecretRef:
      name: letsencrypt-private-key
    # Enable the HTTP-01 challenge provider
    http01: {}
